# These values are set by the deploy builds and are sourced
# by calling Azure App Configuration for the values associated
# with the solution to which the service belongs.  This values
# are set in ./iac/terraform/config/main.tf
tenantId: ""
managedIdentityClientId: ""
appConfigEndpoint: ""
keyVaultName: ""

# The remaining values are set by the builds when deploying a service by 
# passing the service's commmon and environment specific Helm environment 
# vaue files.
solution: ""
service: ""
environment: ""

serviceAccount: ""
port: 0
replicas: 1

extraLabels: {}
podAnnotations: {}
podLabels: {}

extraEnv: {}

image:
  registry: ""
  tag: ""
  pullPolicy: IfNotPresent

probes:
  startupPath: ""
  readinessPath: ""
  livenessPath: ""

resources: 
  requests:
    cpu: 100m
    memory: 500Mi
  limits:
    cpu: 250m
    memory: 750Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

gateway: 
  name: ""
  hosts: []

envNames:
  dev: DEVELOPMENT
  stg: STAGING
  prd: PRODUCTION

appConfigRefreshEnabled: false
