apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "service.name" . }}-app-config-provider
spec:
  endpoint: {{ .Values.appConfigEndpoint }}
  target:
    configMapName: {{ include "service.name" . }}-configs
    configMapData: 
      type: json
      key: app-configurations
  configuration:
    trimKeyPrefixes: ["{{ include "service.name" . }}/"]
    selectors:
      - keyFilter: "{{ include "service.name" . }}/*"
    {{- if .Values.appConfigRefreshEnabled }}    
    refresh:
      enabled: true
      interval: 1m
      monitoring:
        keyValues:
          - key: "{{ include "service.name" . }}/update_sentinel" 
    {{ end }}
  auth:
    workloadIdentity:
      managedIdentityClientId: {{ .Values.managedIdentityClientId }}
  secret:
    target:
      secretName: {{ include "service.name" . }}-config-secrets
    auth:
      workloadIdentity:
        managedIdentityClientId: {{ .Values.managedIdentityClientId }}