apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "service.name" . }}-route
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  {{- range .Values.gateway.hosts}}
    - {{ . | quote }}
  {{- end}}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /{{ (include "solution.name" .) }}/{{ (include "service.name" .) }}/    
        headers:
        - type: Exact
          name: env
          value: {{ .Values.environment }}
      filters: 
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /api/
              type: ReplacePrefixMatch
      backendRefs:
        - name: {{ include "service.name" . }}
          port: 80