apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.port }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}