pool:
  vmImage: ubuntu-latest

name: '1.0.$(Rev:r)'

stages:
- template: ../../../templates/shared/microservice-pipeline.yml
  parameters:
    solutionPath: microservices/Solution.Context/src
    solutionName: [nf:solution-name]
    serviceName: [nf:service-name]
    dockerFilePath: microservices/Solution.Context
    imageVersion: $(Build.BuildNumber)
    chartName: microservice
    chartVersion: '[nf:chart-version]'
